In [1]:
import tensorflow as tf
import cv2
import os
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import time

pygame 2.1.2 (SDL 2.0.18, Python 3.9.16)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'C:\Users\Jayasuriya\models\model.h5')

In [3]:
mixer.init()
sound= mixer.Sound(r'C:\Users\Jayasuriya\Downloads\mrlEyes_2018_01\prepared_data\alarm.wav')

lbl=['Close', 'Open']

path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score = 0

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray,minNeighbors = 3,scaleFactor = 1.1,minSize=(25,25))
    eyes = eye_cascade.detectMultiScale(gray,minNeighbors = 1,scaleFactor = 1.1)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (255,0,0) , 3 )

    for (x,y,w,h) in eyes:

        eye = frame[y:y+h,x:x+w]
        #eye = cv2.cvtColor(eye,cv2.COLOR_BGR2GRAY)
        eye = cv2.resize(eye,(80,80))
        eye = eye/255
        eye = eye.reshape(80,80,3)
        eye = np.expand_dims(eye,axis=0)
        prediction = model.predict(eye)
        print(prediction)
       #Condition for Close
        if prediction[0][0]>0.30:
            cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            score=score+1
            #print("Close Eyes")
            if(score > 20):
                try:
                    sound.play()
                except:  # isplaying = False
                    pass

        #Condition for Open
        elif prediction[0][1] > 0.70:
            score = score - 1
            if (score < 0):
                score = 0
            cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            #print("Open Eyes")
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)

    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[0.11200979 0.8879902 ]]
[[0.06855076 0.9314493 ]]
[[0.65205365 0.34794635]]
[[9.1870754e-07 9.9999905e-01]]
[[1.2087915e-07 9.9999988e-01]]
[[0.654104   0.34589598]]
[[0.9717833 0.0282168]]
[[7.7929928e-07 9.9999917e-01]]
[[2.9047128e-06 9.9999714e-01]]
[[0.11689042 0.8831096 ]]
[[0.6949093  0.30509073]]
[[7.2913253e-10 1.0000000e+00]]
[[1.2906379e-07 9.9999988e-01]]
[[0.6015584  0.39844158]]
[[1.6329037e-04 9.9983668e-01]]
[[4.7229416e-05 9.9995279e-01]]
[[1.0669909e-07 9.9999988e-01]]
[[2.0390248e-06 9.9999797e-01]]
[[1.6626663e-08 1.0000000e+00]]
[[0.24642125 0.7535787 ]]
[[0.44085836 0.55914164]]
[[2.2263431e-10 1.0000000e+00]]
[[0.38191247 0.6180875 ]]
[[6.2778236e-07 9.9999940e-01]]
[[0.2215997  0.77840024]]
[[0.31843418 0.6815658 ]]
[[0.61176836 0.3882316 ]]
[[2.2263431e-10 1.0000000e+00]]
[[6.2778236e-07 9.9999940e-01]]
[[0.3376254  0.66237456]]
[[0.2215997  0.77840024]]
[[0.31843418 0.6815658 ]]
[[0.61176836 0.3882316 ]]
[[7.608239e-08 9.999999e-01]]
[[0.35390925 0.64609075]